spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db
    username: baggio
    password: baggio
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        format_sql: true
stripe:
  enabled: false
